Failure # 1 (occurred at 2023-05-24_14-22-52)
[36mray::ImplicitFunc.train()[39m (pid=2108467, ip=129.241.113.29, repr=hyper_search_train)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 421, in _inner
    return inner(config, checkpoint_dir=None)
  File "/lhome/oskarsto/repos/master-eeg-trans/.venv/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 413, in inner
    return trainable(config, **fn_kwargs)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 164, in hyper_search_train
    fine_tuning_hypersearch(copy.deepcopy(all_params), global_params)
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 248, in fine_tuning_hypersearch
    train_model(epochs, model, train_loader,
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/hyper_search.py", line 263, in train_model
    val_loss, correct_eval_preds, num_eval_preds = validate_epoch_fine(model, val_loader, device, loss_func,
  File "/lhome/oskarsto/repos/master-eeg-trans/DECCaTNet/DECCaTNet_model/fine_tuning.py", line 278, in validate_epoch
    del loss
UnboundLocalError: local variable 'loss' referenced before assignment
